# Generated by Django 2.2.4 on 2019-08-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hellowordAutoComplete', '0002_auto_20190809_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='idPerson',
        ),
        migrations.AddField(
            model_name='person',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hellowordAutoComplete.Estados'),
        ),
    ]
