# Generated by Django 2.2.4 on 2019-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellowordAutoComplete', '0004_auto_20190809_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('idCidade', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCidade', models.CharField(max_length=100)),
            ],
        ),
    ]
