# Generated by Django 2.2.4 on 2019-08-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hellowordAutoComplete', '0006_cidade_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hellowordAutoComplete.Cidade'),
        ),
    ]
